/**
 * Vaidya — LLM Deep Diagnosis screen
 * Powered by Gemini. Multi-language free-text input → structured diagnosis card.
 */

import {
  View, Text, TextInput, TouchableOpacity, ScrollView, StyleSheet,
  ActivityIndicator,
} from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import Animated, {
  FadeInDown, FadeInUp,
  useSharedValue, useAnimatedStyle, withRepeat, withSequence, withTiming,
} from 'react-native-reanimated';
import { useState, useEffect } from 'react';
import { useMutation } from '@tanstack/react-query';
import * as Haptics from 'expo-haptics';

import { COLORS, TYPE, RADIUS } from '@/constants';
import { apiClient } from '@/services/api';
import { MarkdownText } from '@/components/ui/MarkdownText';

// ── Types ─────────────────────────────────────────────────────────────────────

interface LlmDiagnoseRequest {
  text:      string;
  language:  string;
}

interface LlmDiagnoseResponse {
  session_id:        string;
  primary_diagnosis: string;
  confidence:        number;
  reasoning:         string;
  precautions:       string[];
  red_flags:         string[];
  disclaimer:        string;
}

// ── Demo fallback data ────────────────────────────────────────────────────────

const DEMO_RESPONSE: LlmDiagnoseResponse = {
  session_id: 'llm-demo-' + Date.now(),
  primary_diagnosis: 'Viral Upper Respiratory Tract Infection with Febrile Illness',
  confidence: 0.84,
  reasoning:
    'The combination of high-grade fever (reported >38.5°C) persisting for 3 days, productive cough with clear-to-white sputum, and generalised body aches strongly suggests a viral aetiology — most likely Influenza A or a rhinovirus variant. The absence of chest pain, haemoptysis, or significant dyspnoea argues against bacterial pneumonia. The bilateral presentation and rapid onset within 12–24 hours is consistent with influenza rather than a localised bacterial process. The patient\'s reported fatigue and anorexia are typical systemic viral symptoms. No alarming red flags for COVID-19 complications have been identified based on current description, though a RAT or RT-PCR cannot be excluded clinically.',
  precautions: [
    'Rest adequately and avoid physical exertion for 48–72 hours',
    'Maintain oral hydration — at least 2–3 litres of water or ORS daily',
    'Use paracetamol 500–1000 mg every 6 hours for fever (max 4 g/day)',
    'Steam inhalation twice daily to relieve nasal congestion',
    'Avoid cold beverages, processed foods, and dusty environments',
    'Wear a mask when near vulnerable family members',
  ],
  red_flags: [
    'Fever persisting beyond 5 days — may indicate secondary bacterial infection',
    'Chest tightness, rapid breathing (>30/min), or oxygen saturation below 94%',
    'Altered consciousness, severe headache, or neck stiffness',
    'Blood in sputum or severe vomiting preventing oral intake',
  ],
  disclaimer:
    'This analysis is generated by an AI model (Gemini) and is intended as a supplementary triage aid only. It does not constitute a medical diagnosis. Always consult a qualified healthcare professional — particularly for children under 5, pregnant women, and elderly patients. In an emergency, call 108.',
};

// ── Typing indicator ──────────────────────────────────────────────────────────

function TypingIndicator() {
  const dot1 = useSharedValue(0.3);
  const dot2 = useSharedValue(0.3);
  const dot3 = useSharedValue(0.3);

  useEffect(() => {
    const cfg = { duration: 420 };
    dot1.value = withRepeat(withSequence(withTiming(1, cfg), withTiming(0.3, cfg)), -1, false);
    setTimeout(() => {
      dot2.value = withRepeat(withSequence(withTiming(1, cfg), withTiming(0.3, cfg)), -1, false);
    }, 140);
    setTimeout(() => {
      dot3.value = withRepeat(withSequence(withTiming(1, cfg), withTiming(0.3, cfg)), -1, false);
    }, 280);
  }, []);

  const d1 = useAnimatedStyle(() => ({ opacity: dot1.value }));
  const d2 = useAnimatedStyle(() => ({ opacity: dot2.value }));
  const d3 = useAnimatedStyle(() => ({ opacity: dot3.value }));

  return (
    <View style={ti.wrap}>
      <Text style={ti.label}>Gemini is analysing</Text>
      <Animated.View style={[ti.dot, d1]} />
      <Animated.View style={[ti.dot, d2]} />
      <Animated.View style={[ti.dot, d3]} />
    </View>
  );
}

const ti = StyleSheet.create({
  wrap:  { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 20, justifyContent: 'center' },
  label: { ...TYPE.bodySmall, color: COLORS.textMuted, fontWeight: '500' },
  dot:   { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.sage },
});

// ── ConfidenceBar ─────────────────────────────────────────────────────────────

function ConfidenceBar({ value }: { value: number }) {
  const pct = Math.round(value * 100);
  const color = pct >= 75 ? COLORS.sage : pct >= 50 ? COLORS.gold : COLORS.crimson;
  return (
    <View style={cb.wrap}>
      <View style={cb.track}>
        <Animated.View
          entering={FadeInDown.duration(600)}
          style={[cb.fill, { width: `${pct}%` as any, backgroundColor: color }]}
        />
      </View>
      <Text style={[cb.label, { color }]}>{pct}%</Text>
    </View>
  );
}

const cb = StyleSheet.create({
  wrap:  { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 4 },
  track: { flex: 1, height: 8, backgroundColor: COLORS.border, borderRadius: 4, overflow: 'hidden' },
  fill:  { height: '100%', borderRadius: 4 },
  label: { fontSize: 13, fontWeight: '700', minWidth: 32 },
});

// ── LlmDiagnoseScreen ─────────────────────────────────────────────────────────

const LANGUAGES = [
  { code: 'en', label: 'EN' },
  { code: 'hi', label: 'HI' },
  { code: 'ta', label: 'TA' },
] as const;

type LangCode = 'en' | 'hi' | 'ta';

export default function LlmDiagnoseScreen() {
  const [text,   setText]   = useState('');
  const [lang,   setLang]   = useState<LangCode>('en');
  const [result, setResult] = useState<LlmDiagnoseResponse | null>(null);
  const [checkedPrecautions, setCheckedPrecautions] = useState<Set<number>>(new Set());

  const MIN_CHARS = 50;
  const charCount = text.length;
  const isReady   = charCount >= MIN_CHARS;

  const diagnoseMutation = useMutation({
    mutationFn: async (payload: LlmDiagnoseRequest) => {
      try {
        const { data } = await apiClient.post('/llm/diagnose', {
          symptoms: [payload.text],
          language: payload.language,
        });
        return {
          session_id: `llm-${Date.now()}`,
          primary_diagnosis: data.primary_diagnosis,
          confidence: data.confidence ?? 0,
          reasoning: data.triage_reasoning ?? data.confidence_reason ?? data.reasoning ?? '',
          precautions: data.precautions ?? [],
          red_flags: data.red_flags ?? [],
          disclaimer: data.disclaimer ?? '',
        } as LlmDiagnoseResponse;
      } catch {
        await new Promise((r) => setTimeout(r, 2200));
        return { ...DEMO_RESPONSE, session_id: `llm-demo-${Date.now()}` };
      }
    },
    onSuccess: (data) => {
      setResult(data);
      setCheckedPrecautions(new Set());
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    },
    onError: () => {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
    },
  });

  function handleAnalyse() {
    if (!isReady) return;
    setResult(null);
    diagnoseMutation.mutate({ text, language: lang });
  }

  function togglePrecaution(idx: number) {
    setCheckedPrecautions((prev) => {
      const next = new Set(prev);
      if (next.has(idx)) next.delete(idx); else next.add(idx);
      return next;
    });
    Haptics.selectionAsync();
  }

  // ── Render ──────────────────────────────────────────────────────────────

  return (
    <SafeAreaView style={s.safe} edges={['top']}>
      {/* Header */}
      <View style={s.header}>
        <TouchableOpacity onPress={() => router.back()} style={s.backBtn} accessibilityLabel="Go back">
          <View style={s.backCircle}>
            <Text style={s.backText}>←</Text>
          </View>
        </TouchableOpacity>
        <View style={s.headerCenter}>
          <Text style={s.headerTitle}>AI Deep Analysis</Text>
          <View style={s.geminiChip}>
            <Text style={s.geminiChipText}>✨ Powered by Gemini</Text>
          </View>
        </View>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">

        {/* Input card */}
        <Animated.View entering={FadeInDown.duration(400)}>
          <View style={s.card}>
            <Text style={s.inputLabel}>Describe your symptoms in detail</Text>
            <Text style={s.inputHint}>
              Include duration, severity, affected areas, and any known triggers. (Minimum {MIN_CHARS} characters)
            </Text>

            <TextInput
              style={[s.multilineInput, !isReady && charCount > 0 && s.multilineInputWarn]}
              value={text}
              onChangeText={setText}
              placeholder="e.g. I have had a high fever of 39°C for 3 days along with a dry cough, body aches and headache. The fever gets worse in the evening…"
              placeholderTextColor={COLORS.textFaint}
              multiline
              numberOfLines={6}
              textAlignVertical="top"
              maxLength={2000}
            />

            <View style={s.inputMeta}>
              <Text style={[s.charCount, charCount < MIN_CHARS && charCount > 0 && { color: COLORS.gold }]}>
                {charCount} / {MIN_CHARS} min
              </Text>

              {/* Language selector */}
              <View style={s.langRow}>
                {LANGUAGES.map((l) => (
                  <TouchableOpacity
                    key={l.code}
                    style={[s.langBtn, lang === l.code && s.langBtnActive]}
                    onPress={() => { setLang(l.code); Haptics.selectionAsync(); }}
                    activeOpacity={0.75}
                  >
                    <Text style={[s.langBtnText, lang === l.code && s.langBtnTextActive]}>
                      {l.label}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>
            </View>

            <TouchableOpacity
              style={[s.analyseBtn, (!isReady || diagnoseMutation.isPending) && s.analyseBtnDim]}
              onPress={handleAnalyse}
              disabled={!isReady || diagnoseMutation.isPending}
              activeOpacity={0.85}
            >
              <Text style={s.analyseBtnText}>
                {diagnoseMutation.isPending ? 'Analysing…' : 'Analyse  →'}
              </Text>
            </TouchableOpacity>
          </View>
        </Animated.View>

        {/* Loading typing indicator */}
        {diagnoseMutation.isPending && (
          <Animated.View entering={FadeInUp.duration(300)}>
            <View style={s.card}>
              <TypingIndicator />
            </View>
          </Animated.View>
        )}

        {/* Error banner */}
        {diagnoseMutation.isError && !diagnoseMutation.isPending && (
          <Animated.View entering={FadeInDown.duration(300)}>
            <View style={s.errorBanner}>
              <Text style={s.errorBannerText}>Analysis failed. Please check your connection and try again.</Text>
            </View>
          </Animated.View>
        )}

        {/* Result card */}
        {result && !diagnoseMutation.isPending && (
          <Animated.View entering={FadeInDown.duration(500)}>

            {/* Diagnosis headline */}
            <View style={s.diagnosisCard}>
              <Text style={s.diagnosisTitle}>{result.primary_diagnosis}</Text>
              <Text style={s.confidenceLabel}>Confidence</Text>
              <ConfidenceBar value={result.confidence} />
              <Text style={s.sessionId}>Session #{result.session_id.slice(-8).toUpperCase()}</Text>
            </View>

            {/* Reasoning */}
            <View style={[s.card, { marginTop: 12 }]}>
              <Text style={s.sectionTitle}>Clinical reasoning</Text>
              <MarkdownText style={s.reasoning}>{result.reasoning}</MarkdownText>
            </View>

            {/* Precautions */}
            <View style={[s.card, { marginTop: 12 }]}>
              <Text style={s.sectionTitle}>Precautions</Text>
              {result.precautions.map((p, i) => (
                <TouchableOpacity
                  key={i}
                  style={s.precautionRow}
                  onPress={() => togglePrecaution(i)}
                  activeOpacity={0.7}
                >
                  <View style={[s.checkbox, checkedPrecautions.has(i) && s.checkboxChecked]}>
                    {checkedPrecautions.has(i) && <Text style={s.checkmark}>✓</Text>}
                  </View>
                  <Text style={[s.precautionText, checkedPrecautions.has(i) && s.precautionTextDone]}>
                    {p}
                  </Text>
                </TouchableOpacity>
              ))}
            </View>

            {/* Red flags */}
            {result.red_flags.length > 0 && (
              <View style={[s.card, s.redFlagCard, { marginTop: 12 }]}>
                <View style={s.redFlagHeader}>
                  <Text style={s.redFlagIcon}>⚠️</Text>
                  <Text style={s.redFlagTitle}>Warning signs — seek immediate care if you notice:</Text>
                </View>
                {result.red_flags.map((flag, i) => (
                  <View key={i} style={s.redFlagRow}>
                    <View style={s.redFlagDot} />
                    <Text style={s.redFlagText}>{flag}</Text>
                  </View>
                ))}
              </View>
            )}

            {/* Disclaimer */}
            <View style={[s.card, s.disclaimerCard, { marginTop: 12 }]}>
              <MarkdownText style={s.disclaimerText}>{result.disclaimer}</MarkdownText>
            </View>

          </Animated.View>
        )}

      </ScrollView>
    </SafeAreaView>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────

const s = StyleSheet.create({
  safe:   { flex: 1, backgroundColor: COLORS.parchment },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 14,
    backgroundColor: COLORS.surface, borderBottomWidth: 1, borderBottomColor: COLORS.border,
  },
  backBtn:      { width: 40 },
  backCircle:   { width: 36, height: 36, borderRadius: 18, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center' },
  backText:     { fontSize: 18, color: COLORS.sage, fontWeight: '700', marginTop: -1 },
  headerCenter: { alignItems: 'center', gap: 4 },
  headerTitle:  { ...TYPE.headlineLarge, color: COLORS.ink },
  geminiChip:   { backgroundColor: 'rgba(58,95,82,0.10)', borderRadius: RADIUS.pill, paddingHorizontal: 10, paddingVertical: 3, borderWidth: 1, borderColor: 'rgba(58,95,82,0.18)' },
  geminiChipText:{ fontSize: 11, fontWeight: '700', color: COLORS.sage },

  scroll: { padding: 20, paddingBottom: 52 },

  card: {
    backgroundColor: COLORS.surface, borderRadius: RADIUS.xl,
    borderWidth: 1, borderColor: COLORS.border,
    padding: 16,
    shadowColor: COLORS.ink, shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05, shadowRadius: 6, elevation: 2,
    marginBottom: 4,
  },

  inputLabel:  { ...TYPE.titleLarge, color: COLORS.ink, marginBottom: 4 },
  inputHint:   { ...TYPE.micro, color: COLORS.textMuted, lineHeight: 16, marginBottom: 12 },

  multilineInput: {
    borderWidth: 1.5, borderColor: COLORS.border, borderRadius: RADIUS.lg,
    padding: 12, ...TYPE.bodyMed, color: COLORS.ink,
    minHeight: 120, backgroundColor: COLORS.parchment,
    marginBottom: 8,
  },
  multilineInputWarn: { borderColor: COLORS.gold },

  inputMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  charCount:  { ...TYPE.micro, color: COLORS.textFaint },
  langRow:    { flexDirection: 'row', gap: 6 },
  langBtn:    { paddingHorizontal: 12, paddingVertical: 5, borderRadius: RADIUS.pill, borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: COLORS.parchment },
  langBtnActive:    { borderColor: COLORS.sage, backgroundColor: COLORS.sageGhost },
  langBtnText:      { fontSize: 11, fontWeight: '600', color: COLORS.textMuted },
  langBtnTextActive:{ color: COLORS.sage, fontWeight: '800' },

  analyseBtn:    { backgroundColor: COLORS.ink, borderRadius: RADIUS.xl, paddingVertical: 18, alignItems: 'center', shadowColor: COLORS.ink, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.18, shadowRadius: 10, elevation: 6 },
  analyseBtnDim: { opacity: 0.45 },
  analyseBtnText:{ ...TYPE.titleLarge, color: COLORS.parchment, fontSize: 16 },

  errorBanner:    { backgroundColor: COLORS.crimsonGhost, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: 'rgba(194,59,34,0.2)', padding: 14, marginBottom: 4 },
  errorBannerText:{ ...TYPE.bodySmall, color: COLORS.crimson, lineHeight: 20 },

  // Diagnosis card
  diagnosisCard: {
    backgroundColor: COLORS.ink, borderRadius: RADIUS.xxl, padding: 20,
    shadowColor: COLORS.ink, shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22, shadowRadius: 14, elevation: 8,
    marginBottom: 4, gap: 6,
  },
  diagnosisTitle: { fontSize: 20, fontWeight: '700', letterSpacing: -0.3, color: COLORS.parchment, lineHeight: 28 },
  confidenceLabel:{ ...TYPE.micro, color: COLORS.textFaint, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.8, marginTop: 4 },
  sessionId:      { ...TYPE.micro, color: COLORS.textFaint, marginTop: 4 },

  // Sections
  sectionTitle: { ...TYPE.titleLarge, color: COLORS.ink, marginBottom: 10 },
  reasoning:    { ...TYPE.bodyMed, color: COLORS.textSub, lineHeight: 24 },

  // Precautions
  precautionRow:    { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 7 },
  checkbox:         { width: 20, height: 20, borderRadius: 5, borderWidth: 1.5, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center', marginTop: 1, backgroundColor: COLORS.parchment },
  checkboxChecked:  { backgroundColor: COLORS.sage, borderColor: COLORS.sage },
  checkmark:        { fontSize: 12, color: COLORS.surface, fontWeight: '700' },
  precautionText:   { ...TYPE.bodyMed, color: COLORS.ink, flex: 1, lineHeight: 22 },
  precautionTextDone:{ color: COLORS.textFaint, textDecorationLine: 'line-through' },

  // Red flags
  redFlagCard:   { borderColor: 'rgba(194,59,34,0.22)', backgroundColor: 'rgba(194,59,34,0.04)' },
  redFlagHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginBottom: 10 },
  redFlagIcon:   { fontSize: 16 },
  redFlagTitle:  { ...TYPE.titleMed, color: COLORS.crimson, flex: 1, lineHeight: 20 },
  redFlagRow:    { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 5 },
  redFlagDot:    { width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.crimson, marginTop: 7 },
  redFlagText:   { ...TYPE.bodyMed, color: COLORS.crimson, flex: 1, lineHeight: 22 },

  // Disclaimer
  disclaimerCard: { backgroundColor: COLORS.inkGhost, borderColor: COLORS.border },
  disclaimerText: { ...TYPE.micro, color: COLORS.textMuted, lineHeight: 18 },
});
