"""
Vaidya — Custom Prometheus metrics registry

Centralised module so all metric objects are singletons.
Import from here — never instantiate metrics in service files directly.

Usage:
    from app.core.metrics import INFERENCE_TIME, TRIAGE_COUNTER, record_inference

    # Context-manager style (recommended):
    with INFERENCE_TIME.labels(model="nlp").time():
        result = classifier.predict(features)

    # Manual style:
    start = time.perf_counter()
    result = run_llm(prompt)
    INFERENCE_TIME.labels(model="llm_fallback").observe(time.perf_counter() - start)

    # Triage counter:
    TRIAGE_COUNTER.labels(district="vellore", severity="P3", source="xgboost").inc()

Metrics exposed at GET /metrics (Prometheus scrape endpoint).
Grafana dashboard panels:
  - vaidya_model_inference_seconds_bucket  → latency heatmap per model
  - vaidya_triage_total                    → triage volume by district + severity
  - vaidya_llm_fallback_total              → fallback rate (signals low NLP confidence)
  - vaidya_offline_inference_total         → offline usage ratio
  - vaidya_consent_grant_total             → DPDP consent funnel
"""

import time
from contextlib import contextmanager
from typing import Generator

from prometheus_client import Counter, Gauge, Histogram, Summary

# ── Model inference latency ────────────────────────────────────────────────────
# Tracks how long each model type takes to run.
# Labels:
#   model: nlp | audio | vision | llm_fallback | fusion
# Buckets tuned for rural server (Raspberry Pi 4 baseline ~200ms NLP):
INFERENCE_TIME = Histogram(
    "vaidya_model_inference_seconds",
    "Model inference latency in seconds",
    labelnames=["model"],
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
)

# ── Triage volume by district + severity ───────────────────────────────────────
# Core operational metric: how many cases per district, per triage level, per source.
# Labels:
#   district: NHM district code (e.g. "TN-VEL", "TN-MDU") or "unknown"
#   severity: P1 (emergency) | P2 (urgent) | P3 (PHC) | P4 (monitor) | P5 (self-care)
#   source:   xgboost | llm_fallback | fusion | offline_tflite
TRIAGE_COUNTER = Counter(
    "vaidya_triage_total",
    "Total triage sessions processed",
    labelnames=["district", "severity", "source"],
)

# ── LLM fallback rate ──────────────────────────────────────────────────────────
# A rising ratio of llm_fallback / total indicates the NLP/XGBoost pipeline
# is struggling with the symptom vocabulary in the field — signal to retrain.
LLM_FALLBACK_COUNTER = Counter(
    "vaidya_llm_fallback_total",
    "Times LLM fallback was triggered (low XGBoost confidence)",
    labelnames=["reason"],  # low_confidence | insufficient_symptoms | parse_error
)

# ── Offline inference usage ────────────────────────────────────────────────────
# Tracks how often patients use the offline TFLite path vs online API.
# Helps size the offline model priority for the next release.
OFFLINE_INFERENCE_COUNTER = Counter(
    "vaidya_offline_inference_total",
    "TFLite offline inference calls",
    labelnames=["result"],  # success | insufficient_symptoms | model_unavailable
)

# ── DPDP consent funnel ────────────────────────────────────────────────────────
# Tracks consent grant/revoke events. Useful for DPO reports.
CONSENT_COUNTER = Counter(
    "vaidya_consent_total",
    "Consent grant and revoke events",
    labelnames=["type", "action"],  # type: data_processing|analytics|asha_contact; action: grant|revoke
)

# ── Active triage sessions gauge ──────────────────────────────────────────────
# In-flight sessions (start: +1, complete/error: -1).
# Spikes indicate latency issues or stuck requests.
ACTIVE_SESSIONS = Gauge(
    "vaidya_active_triage_sessions",
    "Number of triage sessions currently being processed",
)

# ── External API call latency ─────────────────────────────────────────────────
# Tracks latency of calls to Overpass, Nominatim, ABDM, eSanjeevani.
# Labels:
#   service: overpass | nominatim | abdm | esanjeevani | gemini | fcm | twilio
#   status:  success | error | timeout | cache_hit
EXTERNAL_API_TIME = Histogram(
    "vaidya_external_api_seconds",
    "External API call latency",
    labelnames=["service", "status"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 15.0],
)

# ── ASHA notification delivery ────────────────────────────────────────────────
ASHA_NOTIFICATION_COUNTER = Counter(
    "vaidya_asha_notification_total",
    "ASHA worker notifications sent",
    labelnames=["channel", "status"],  # channel: fcm|sms; status: sent|failed|skipped
)

# ── Outbreak alert counter ─────────────────────────────────────────────────────
OUTBREAK_ALERT_COUNTER = Counter(
    "vaidya_outbreak_alerts_total",
    "Outbreak alerts generated by anomaly detection",
    labelnames=["district", "disease", "severity"],  # severity: watch|alert|critical
)


# ── Convenience helpers ────────────────────────────────────────────────────────

@contextmanager
def time_inference(model: str) -> Generator[None, None, None]:
    """Context manager for timing model inference."""
    start = time.perf_counter()
    try:
        yield
    finally:
        elapsed = time.perf_counter() - start
        INFERENCE_TIME.labels(model=model).observe(elapsed)


def record_triage(
    district: str,
    triage_level: int,
    source: str,
) -> None:
    """
    Record a completed triage event.

    Maps triage_level (1-5) to a severity label that is more meaningful
    in Grafana dashboards than a bare integer:
      5 → P1 (Emergency)
      4 → P2 (Urgent)
      3 → P3 (PHC)
      2 → P4 (Monitor)
      1 → P5 (Self-care)
    """
    severity_map = {5: "P1", 4: "P2", 3: "P3", 2: "P4", 1: "P5"}
    severity = severity_map.get(triage_level, "unknown")
    district_code = district.strip() if district else "unknown"
    TRIAGE_COUNTER.labels(
        district=district_code,
        severity=severity,
        source=source,
    ).inc()


def record_external_api(
    service: str,
    status: str,
    elapsed_s: float,
) -> None:
    """Record an external API call result."""
    EXTERNAL_API_TIME.labels(service=service, status=status).observe(elapsed_s)
